const fs = require("fs");

let code = fs.readFileSync("generate-html.cjs", "utf8");

// Define the updated mbbsCountries array with human-written, keyword-rich copy
const updatedMBBSCountries = `const mbbsCountries = [
  {
    slug: "georgia",
    name: "Georgia",
    flag: "🇬🇪",
    tagline: "Affordable MBBS in Georgia with European standards",
    duration: "6 Years",
    fees: "₹ 25 – 35 Lacs (Total)",
    language: "English Medium",
    intakes: ["September", "March"],
    topUniversities: ["Tbilisi State Medical University", "Ivane Javakhishvili Tbilisi State University", "David Tvildiani Medical University", "Batumi Shota Rustaveli State University"],
    highlights: ["NMC & WHO Approved", "No Entrance Exam", "Easy Visa Process", "Indian Food Available", "Low Cost of Living"],
    description: "Studying MBBS in Georgia is currently one of the most practical and popular pathways for Indian medical aspirants. Many NMC approved medical universities and MCI approved universities in Georgia provide top-class, English-medium medical education. With TrueMark Edu, a leading MBBS abroad consultant, you can secure direct MBBS admission abroad with 100% MBBS seat confirmation and absolutely zero hidden costs. For any NEET qualified MBBS abroad seeker, Georgia offers European-standard clinical training and excellent campus life without requiring any donation.",
    eligibility: ["NEET Qualified", "50% in PCB (General) / 40% (SC/ST)", "17+ years of age", "English Proficiency - Basic"],
    hostel: "University hostels with 2/3 sharing rooms, attached washrooms, Wi-Fi & laundry. Cost approx ₹ 30,000/month.",
    food: "Indian food, tiffin services and full mess available in and around campus.",
    recognition: ["NMC (National Medical Commission)", "WHO (World Health Organization)", "ECFMG - USA", "GMC - UK"],
    fmge: "Eligible for FMGE / NExT screening test conducted by NMC.",
    process: ["1. Free Counseling", "2. Application Submission", "3. Offer Letter", "4. Invitation Letter", "5. Visa Processing", "6. Departure & Airport Pickup"]
  },
  {
    slug: "uzbekistan",
    name: "Uzbekistan",
    flag: "🇺🇿",
    tagline: "Cheapest MBBS abroad under 20 Lakhs",
    duration: "6 Years",
    fees: "₹ 18 – 22 Lacs (Total)",
    language: "English Medium",
    intakes: ["September", "February"],
    topUniversities: ["Tashkent Medical Academy", "Samarkand State Medical Institute", "Bukhara State Medical Institute", "Fergana Medical Institute"],
    highlights: ["Lowest total fees", "100% NMC approved", "Direct admission", "Safe country", "MCI passing rate high"],
    description: "If you are looking for the cheapest MBBS abroad option, Uzbekistan is the ultimate destination for Indian students. Many NMC approved medical universities in Uzbekistan offer top-tier, MCI approved medical programs. You can complete your entire MBBS under 25 lakhs, which includes tuition, comfortable hostel accommodation, and Indian mess services. Our experts at TrueMark Edu—one of India's most reliable MBBS consultants in India—ensure smooth direct MBBS admission abroad. We handle your documents, visa, and university approvals to guarantee hassle-free MBBS seat confirmation.",
    eligibility: ["NEET Qualified", "50% in PCB", "Age 17+", "No IELTS required"],
    hostel: "Government hostels with Indian students block, 24/7 security, kitchen.",
    food: "Full Indian mess available in hostel premises. North & South Indian cuisine.",
    recognition: ["NMC Approved", "WHO Listed", "WFME Recognized"],
    fmge: "Fully eligible for FMGE/NExT. High passing ratio among Indian students.",
    process: ["1. Registration", "2. Document verification", "3. University offer", "4. Visa", "5. Fly to Uzbekistan"]
  },
  {
    slug: "kazakhstan",
    name: "Kazakhstan",
    flag: "🇰🇿",
    tagline: "Top-ranked medical universities in Central Asia",
    duration: "5 Years + 1 Year Internship",
    fees: "₹ 22 – 30 Lacs (Total)",
    language: "English Medium",
    intakes: ["September", "March"],
    topUniversities: ["Al-Farabi Kazakh National University", "Kazakh National Medical University", "Karaganda State Medical University", "Astana Medical University"],
    highlights: ["Ranked universities", "Modern infrastructure", "MCI approved", "Indian diaspora", "Affordable"],
    description: "Choosing to study MBBS in Kazakhstan is a highly rewarding choice for Indian medical students. It ranks as a premier destination for studying MBBS abroad, featuring well-equipped modern clinics and world-class faculty. Kazakhstan is home to top-tier NMC approved medical universities and MCI approved universities that run fully English-medium courses. TrueMark Edu, a premier study abroad consultancy, guides you from initial profiling to direct MBBS admission abroad. Our solid support ensures hassle-free NEET qualified MBBS abroad processing with zero donation, enabling easy MBBS seat confirmation.",
    eligibility: ["NEET Qualified", "50% in PCB", "17+ age"],
    hostel: "On-campus modern hostels with single/double rooms.",
    food: "Indian food mess and tiffin services available.",
    recognition: ["NMC", "WHO", "ECFMG"],
    fmge: "Eligible for NExT/FMGE screening.",
    process: ["Counseling → Application → Offer → Visa → Departure"]
  },
  {
    slug: "russia",
    name: "Russia",
    flag: "🇷🇺",
    tagline: "Globally-recognized medical universities with 60+ years of excellence",
    duration: "6 Years",
    fees: "₹ 30 – 45 Lacs (Total)",
    language: "English Medium",
    intakes: ["September", "March"],
    topUniversities: ["Kazan Federal University", "Moscow State Medical University", "Northern State Medical University", "Bashkir State Medical University"],
    highlights: ["Top 100 global medical universities", "Low cost of living", "Indian mess", "Government universities"],
    description: "Studying MBBS in Russia remains a highly preferred pathway for Indian medical students. For decades, Russia has provided globally recognized medical degrees through its top NMC approved medical universities and MCI approved universities. As a leading MBBS abroad consultant, TrueMark Edu helps you navigate the entire process for direct MBBS admission abroad. We ensure you get verified English-medium medical colleges with excellent clinical training, comfortable student housing with Indian mess, and reliable NExT exam preparation abroad to secure your future career.",
    eligibility: ["NEET Qualified", "50% in PCB", "17+ years"],
    hostel: "Well-furnished hostels with Indian students' accommodation.",
    food: "Indian mess available on campus.",
    recognition: ["NMC", "WHO", "UNESCO"],
    fmge: "Eligible for NExT/FMGE.",
    process: ["1. Counseling 2. Application 3. Offer 4. Visa 5. Departure"]
  },
  {
    slug: "kyrgyzstan",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    tagline: "Budget-friendly MBBS in Central Asia",
    duration: "6 Years",
    fees: "₹ 20 – 28 Lacs (Total)",
    language: "English Medium",
    intakes: ["September", "March"],
    topUniversities: ["Asian Medical Institute", "Kyrgyz State Medical Academy", "International School of Medicine"],
    highlights: ["Affordable fees", "NMC approved", "Direct admission", "Indian mess"],
    description: "For students searching for the cheapest MBBS abroad, Kyrgyzstan offers an incredibly budget-friendly option to study MBBS abroad under 25 lakhs. All top medical colleges in Kyrgyzstan are NMC approved medical universities and MCI approved universities offering English-medium MBBS courses. TrueMark Edu—the most trusted MBBS consultants in India—assists you with direct MBBS admission abroad, handling everything from documentation to visa clearance. For any NEET qualified MBBS abroad candidate, Kyrgyzstan offers a great balance of low living costs and quality clinical training.",
    eligibility: ["NEET Qualified", "50% in PCB"],
    hostel: "Hostel facilities with Indian food mess.",
    food: "North Indian and South Indian food available.",
    recognition: ["NMC", "WHO"],
    fmge: "Eligible for NExT.",
    process: ["Counseling → Application → Visa → Fly"]
  },
  {
    slug: "st-lucia",
    name: "St. Lucia",
    flag: "🇱🇨",
    tagline: "Caribbean MBBS with US curriculum & clinical rotations",
    duration: "4.5 Years + 1 Year Rotation",
    fees: "₹ 25 – 35 Lacs (Total)",
    language: "English Medium",
    intakes: ["January", "May", "September"],
    topUniversities: ["Aureus University School of Medicine", "Spartan Health Sciences University", "University of Science, Arts & Technology"],
    highlights: ["US-based curriculum", "Clinical rotation in USA", "Direct admission", "English speaking country"],
    description: "Studying MBBS in St. Lucia offers a premium Caribbean medical education following the US curriculum. This is a brilliant pathway for students who want to study MBBS abroad and transition to clinical rotations in USA, UK, or Canada. TrueMark Edu—your dedicated study abroad consultancy—facilitates direct MBBS admission abroad in MCI approved universities in St. Lucia. Our counselors provide end-to-end guidance to secure your MBBS seat confirmation and prepare you with high-quality USMLE and NExT exam preparation abroad.",
    eligibility: ["12th pass with PCB", "NEET qualified", "Basic English"],
    hostel: "On-campus hostels with modern amenities.",
    food: "International and Indian cuisine.",
    recognition: ["ECFMG eligible", "WHO", "CAAM-HP"],
    fmge: "Eligible for NExT/FMGE.",
    process: ["Application → Screening → Offer → Visa → Enrollment"]
  },
  {
    slug: "india",
    name: "India",
    flag: "🇮🇳",
    tagline: "Deemed & Private MBBS admissions without donation",
    duration: "5.5 Years + 1 Year Internship",
    fees: "₹ 40 – 1.2 Cr (Total)",
    language: "English / Regional",
    intakes: ["August / September"],
    topUniversities: ["KMC Manipal", "CMC Vellore", "St. Johns Bangalore", "AIIMS (through NEET)"],
    highlights: ["Direct admission support", "Management & NRI quota", "Top private colleges"],
    description: "We help Indian students secure MBBS seats in top deemed and private medical colleges across India through counseling and admission guidance. Avoid massive donations and secure reliable MBBS seat confirmation through legal counseling channels.",
    eligibility: ["NEET qualified with good rank", "12th PCB 50%"],
    hostel: "College hostels available.",
    food: "Indian mess on campus.",
    recognition: ["NMC"],
    fmge: "Not required (Indian degree).",
    process: ["NEET counseling guidance, choice filling, document verification, admission."]
  }
];`;

// Define the updated europeCountries array
const updatedEuropeCountries = `const europeCountries = [
  {
    slug: "italy",
    name: "Italy",
    flag: "🇮🇹",
    tagline: "MBBS through IMAT - Free education in public universities",
    duration: "6 Years",
    fees: "₹ 8 – 25 Lacs (Total)",
    language: "English Medium",
    intakes: ["September"],
    topUniversities: ["Sapienza University of Rome", "University of Milan", "University of Bologna", "University of Pavia", "Humanitas University"],
    highlights: ["Free tuition in public universities", "IMAT entrance", "European life", "Scholarships available"],
    description: "Pursuing MBBS in Italy is a dream come true for Indian students seeking free or low-tuition education in Europe. By cracking the IMAT (International Medical Admission Test), you can gain admission to world-renowned public medical universities in Italy. This provides a direct pathway for MBBS in Schengen and MBBS in EU countries. TrueMark Edu is the leading MBBS abroad consultant helping students with comprehensive IMAT coaching, extensive document verification (Declaration of Value), and visa guidance. We ensure a smooth process for studying MBBS in Europe for Indian students with 100% transparency.",
    eligibility: ["NEET Qualified", "50% PCB", "IMAT Score", "17+ age"],
    hostel: "Student accommodation and private apartments.",
    food: "Indian restaurants and kitchens available in major cities.",
    recognition: ["NMC", "WHO", "EU Recognized"],
    fmge: "Eligible for NExT/FMGE.",
    process: ["IMAT Registration → Exam → Ranking → Enrollment → Visa"]
  },
  {
    slug: "spain",
    name: "Spain",
    flag: "🇪🇸",
    tagline: "MBBS & Medical PG in Europe's top destination",
    duration: "6 Years (MBBS)",
    fees: "₹ 40 – 70 Lacs (Total)",
    language: "English / Spanish",
    intakes: ["September"],
    topUniversities: ["University of Barcelona", "Autonomous University of Madrid", "University of Navarra", "University of Valencia"],
    highlights: ["PG pathway after MBBS", "EU lifestyle", "Clinical training", "Global degree"],
    description: "Studying MBBS in Spain offers a world-class opportunity for studying MBBS in Europe for Indian students. Spain's top medical schools are globally ranked MCI approved universities, providing extensive clinical training in state-of-the-art hospitals. Spain also offers a clear pathway to medical PG in Europe. TrueMark Edu—one of India's premier MBBS consultants in India—assists you with direct MBBS admission abroad, visa processing, and language training. This is a perfect path for students looking for MBBS in EU countries with a high-quality global standard.",
    eligibility: ["NEET Qualified", "50% PCB", "Spanish proficiency helpful"],
    hostel: "Student residences, shared flats.",
    food: "Mediterranean & Indian food easily available.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["Application → University assessment → Visa → Enrollment"]
  },
  {
    slug: "romania",
    name: "Romania",
    flag: "🇷🇴",
    tagline: "EU MBBS at Carol Davila & top universities",
    duration: "6 Years",
    fees: "₹ 40 – 60 Lacs (Total)",
    language: "English Medium",
    intakes: ["October"],
    topUniversities: ["Carol Davila University of Medicine and Pharmacy Bucharest", "Grigore T. Popa University of Medicine Iasi", "University of Medicine and Pharmacy Cluj-Napoca"],
    highlights: ["EU degree", "NMC approved", "Top medical universities", "Schengen country"],
    description: "If you want to study MBBS in Romania, you will be receiving a globally recognized degree from an EU-member country. Romania is now part of the Schengen area, allowing you to easily travel and explore MBBS in Schengen nations. Highly prestigious medical schools like Carol Davila University of Medicine and Pharmacy in Bucharest are fully NMC approved medical universities. TrueMark Edu, a leading study abroad consultancy, helps you secure direct MBBS admission abroad in Romania, offering high-quality clinical training and reliable NExT exam preparation abroad.",
    eligibility: ["NEET Qualified", "50% PCB", "University entrance test"],
    hostel: "University hostels and private accommodation.",
    food: "Indian restaurants available in Bucharest.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT/FMGE.",
    process: ["1. Application 2. Entrance exam 3. Visa 4. Enrollment"]
  },
  {
    slug: "bulgaria",
    name: "Bulgaria",
    flag: "🇧🇬",
    tagline: "Affordable EU MBBS - Sofia University",
    duration: "6 Years",
    fees: "₹ 35 – 55 Lacs (Total)",
    language: "English Medium",
    intakes: ["October"],
    topUniversities: ["Sofia Medical University", "Plovdiv Medical University", "Varna Medical University"],
    highlights: ["EU Member", "Schengen candidate", "English medium", "Low cost"],
    description: "Studying MBBS in Bulgaria is an excellent, cost-effective option for students looking for MBBS in EU countries. Flagship institutions like Sofia University (Sofia Medical University) are highly respected worldwide and are fully NMC approved medical universities. They offer English-medium MBBS courses with great practical training. TrueMark Edu—your reliable MBBS abroad consultant—guides you through the university entrance tests, document legalization, and student visa filing, ensuring you secure your MBBS seat confirmation in Bulgaria with peace of mind.",
    eligibility: ["NEET", "50% PCB", "Entrance test"],
    hostel: "Hostel and private housing.",
    food: "Indian food outlets available.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["Application → Entrance → Offer → Visa"]
  },
  {
    slug: "czech",
    name: "Czech Republic",
    flag: "🇨🇿",
    tagline: "Ostrava University - Top European medical education",
    duration: "6 Years",
    fees: "₹ 70 – 90 Lacs (Total)",
    language: "English Medium",
    intakes: ["September"],
    topUniversities: ["Ostrava University", "Masaryk University", "Palacky University"],
    highlights: ["Ostrava University", "Top EU research", "High FMGE passing"],
    description: "Pursuing MBBS in Czech Republic is a premium choice for students looking for MBBS in EU countries. Ostrava University and other prestigious medical schools in the Czech Republic are highly coveted due to their research-focused curriculum. These are world-renowned, NMC approved medical universities that have consistently delivered some of the highest FMGE coaching abroad and NExT exam preparation abroad success rates. TrueMark Edu helps you with entrance exam preparation, university admission, and student visa filing to ensure a seamless direct MBBS admission abroad.",
    eligibility: ["NEET Qualified", "50% PCB", "University entrance test (Biology, Chemistry)"],
    hostel: "Student dormitories & apartments.",
    food: "Indian restaurants in Ostrava.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT. Excellent pass percentage.",
    process: ["Apply → Entrance Exam → Enroll → Visa"]
  },
  {
    slug: "slovakia",
    name: "Slovakia",
    flag: "🇸🇰",
    tagline: "EU MBBS in the heart of Europe",
    duration: "6 Years",
    fees: "₹ 60 – 80 Lacs (Total)",
    language: "English Medium",
    intakes: ["September"],
    topUniversities: ["Comenius University Bratislava", "Pavol Jozef Safarik University Kosice", "University of Trnava"],
    highlights: ["EU & Schengen", "English medium", "Safe country"],
    description: "Slovakia offers a secure, peaceful, and world-class environment for pursuing MBBS in Europe for Indian students. Slovakian medical schools, like Comenius University, are prestigious MCI approved universities that offer fully English-medium medical programs. As a premier study abroad consultancy, TrueMark Edu provides comprehensive support for direct MBBS admission abroad in Slovakia. We handle your university registration, visa documentation, and local translation to ensure a smooth transition into MBBS in Schengen zone.",
    eligibility: ["NEET Qualified", "50% PCB", "Entrance test"],
    hostel: "Student hostels and apartments.",
    food: "Indian food and dining options.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["Application → Entrance → Offer → Visa"]
  }
];`;

// Define the updated universities array
const updatedUniversities = `const universities = [
  {
    slug: "carol-davila-bucharest",
    name: "Carol Davila University of Medicine and Pharmacy",
    country: "Romania",
    flag: "🇷🇴",
    qs: "Top 200",
    fees: "₹ 7 – 9 Lacs/Year",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET Qualified", "50% in PCB", "University Entrance Exam"],
    hostel: "On-campus dormitory available at approx ₹ 25,000/month.",
    food: "Indian restaurants and mess facility available nearby.",
    recognition: ["NMC", "WHO", "EU", "WFME"],
    fmge: "Eligible for NExT/FMGE.",
    process: ["Counseling → Entrance → Offer → Visa → Departure"]
  },
  {
    slug: "ostrava-university",
    name: "Ostrava University, Ostrava",
    country: "Czech Republic",
    flag: "🇨🇿",
    qs: "#153 QS World",
    fees: "₹ 12 – 15 Lacs/Year",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET Qualified", "50% PCB", "Entrance Test"],
    hostel: "Student dormitory with meals available.",
    food: "Indian mess and restaurants in Ostrava.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "NExT eligible. High pass rate.",
    process: ["Application → Entrance → Offer → Visa"]
  },
  {
    slug: "semmelweis-university",
    name: "Semmelweis University, Budapest",
    country: "Hungary",
    flag: "🇭🇺",
    qs: "Top 250",
    fees: "₹ 10 – 13 Lacs/Year",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET", "50% PCB", "Entrance test"],
    hostel: "Hostels near campus.",
    food: "Indian food nearby.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["Apply → Entrance → Visa → Fly"]
  },
  {
    slug: "sofia-medical-university",
    name: "Sofia Medical University",
    country: "Bulgaria",
    flag: "🇧🇬",
    qs: "Top EU Medical",
    fees: "₹ 6 – 8 Lacs/Year",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET", "50% PCB", "Entrance"],
    hostel: "Hostel available.",
    food: "Indian food available.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["Apply → Exam → Visa → Fly"]
  },
  {
    slug: "university-of-warsaw",
    name: "University of Warsaw",
    country: "Poland",
    flag: "🇵🇱",
    qs: "Top 300",
    fees: "₹ 8 – 12 Lacs/Year",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET", "50% PCB", "Entrance"],
    hostel: "Student housing.",
    food: "Indian options.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "NExT eligible.",
    process: ["Apply → Exam → Visa"]
  },
  {
    slug: "sapienza-university-rome",
    name: "Sapienza University of Rome",
    country: "Italy",
    flag: "🇮🇹",
    qs: "#134 QS",
    fees: "₹ 1 – 3 Lacs/Year (public)",
    duration: "6 Years",
    language: "English",
    eligibility: ["NEET", "50% PCB", "IMAT Score"],
    hostel: "Student accommodation.",
    food: "Indian mess & restaurants.",
    recognition: ["NMC", "WHO", "EU"],
    fmge: "Eligible for NExT.",
    process: ["IMAT → Rank → Enroll → Visa"]
  }
];`;

// We will find the old arrays in `generate-html.cjs` and replace them.
// Let's use clean block replacements.

const oldMBBSCountriesRegex = /const mbbsCountries = \[\s*\{[\s\S]*?\}\s*\];/;
const oldEuropeCountriesRegex = /const europeCountries = \[\s*\{[\s\S]*?\}\s*\];/;
const oldUniversitiesRegex = /const universities = \[\s*\{[\s\S]*?\}\s*\];/;

code = code.replace(oldMBBSCountriesRegex, updatedMBBSCountries);
code = code.replace(oldEuropeCountriesRegex, updatedEuropeCountries);
code = code.replace(oldUniversitiesRegex, updatedUniversities);

fs.writeFileSync("generate-html.cjs", code);
console.log("Database arrays successfully updated with human-written, keyword-rich SEO copywriting!");
